name: beacontools

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS depedencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libbluetooth-dev 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[scan,dev,test]
    - name: Lint with pylint
      run: |
        pylint beacontools
    - name: Check setup.py
      run: |
        python setup.py check -m -r -s
    - name: Check manifest
      run: |
        check-manifest --ignore tox.ini,pylintrc,requirements_test.txt,tests/*
    - name: Test with pytest
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pytest --cov beacontools
        coveralls

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install Coveralls
      run: |
        python -m pip install --upgrade pip
        pip install coveralls PyYAML
    - name: Finish Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        coveralls --finish